### ISSUE TITLE
[question] does this organization allow to host tmux plugin project?

### ISSUE THREAD

**Issue by Freed-Wu** [tmux-plugins/list#41]
Does this organization allow to host tmux plugin project like [zsh-user](https://github.com/zsh-users) for zsh plugin and [sphinx-contrib](https://github.com/sphinx-contrib) for sphinx plugin? TIA!

**Comment by Freed-Wu** [comment]
Hey @bruno- there are my tmux plugins:

- [tmux-digit](https://github.com/Freed-Wu/tmux-digit) Display digit sign in #S and #I of tmux
- [tmux-bitahub](https://github.com/Freed-Wu/tmux-bitahub) Display bitahub GPU status in tmux status line.

And can they be added to the list?

**Comment by bruno-** [comment]
Hi,
yes, sure. Just open a PR
